### ISSUE TITLE
Sqrt of a number (Binary Search)

### ISSUE THREAD

**Issue by PrinceSah09** [PrinceSah09/HacktoberFest2023#9]

**Comment by AD11-web** [comment]
@PrinceSah09  I would like to contribute on this, assign me

**Comment by nancy-singh10** [comment]
Scrapping upcoming hackathons and events.
@PrinceSah09  I want to work on this issue under hacktober fest.

**Comment by Rudrik01** [comment]
@PrinceSah09  I would like to contribute in issue, can you please assign me this task

**Comment by sahil5910** [comment]
Hey, I am well versed in multiple coding languages i would like to contribute to this issue, can you assign this to me

**Comment by PooniaPankaj** [comment]
Hello sir I am well versed with c++ and I am having a good knowledge of these topics plz assign it to me

**Comment by abhayanand08** [comment]
@PrinceSah09 I would like to contribute in this issue, can you please assign me this task. I can give a great and efficient approach for this.

**Comment by ADNAAN18** [comment]
@PrinceSah09 I would like to contribute to this issue and I can provide solutions from brute force to optimized approach in different programming languages.

**Comment by prateekpr17** [comment]
Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

**Comment by kritika1202** [comment]
sirr, I would be like to contribute to this issue . Please assign this task to me.

**Comment by annihilon** [comment]
I'm eager to demonstrate my skills on this issue. Could you please assign me the task to me ?
